### ISSUE TITLE
Get bindings for a graphql-yoga api

### ISSUE THREAD

**Issue by tibotiber** [prisma/prisma-binding#133]
Hi, I just wanted to highlight I've used this to wrap my graphql-yoga api as well. I have multiple microservices in my setup and some of them now use a prisma-binding to query / mutate stuff from yoga.
```javascript
const api = new Prisma({
  typeDefs: '../api/src/schema.graphql', // that's the yoga one
  endpoint: process.env.API_ENDPOINT, // that's the yoga one
  secret: 'nosecret' // this is fake but required
})
```
This was just way simpler than managing to get `graphql-binding` working with a remote schema.

So questions:
- Am I grossly missing something?
- Should a `remote-graphql-binding` be extracted out of this? What would the diff with `prisma-binding` be then? Or should it be integrated to `graphql-binding`?

Probably related: https://github.com/graphql-binding/graphql-binding/issues/53

**Comment by schickling** [comment]
Thanks a lot for bringing this up @tibotiber. We're currently working on improved tooling to create your own GraphQL bindings. Expect something shortly which hopefully solves your question!

**Comment by tibotiber** [comment]
Neat, looking forward to it. Feel free to close the issue when you feel it's appropriate.

**Comment by maticzav** [comment]
@tibotiber I believe the latest version of `graphql-binding` should acquaint you with the tools you need to gain desired functionality. There's nothing wrong in using `prisma-binding` functionality as long as you are aware of limitations it might have due to serving a non-Prisma endpoint. One such example might be the `exists` query.

I believe this issue is also no longer in sync with the current version of `prisma-binding`, that's why I'll close it.

Feel free to reopen the issue if you believe we should further discuss its content. 🙂
