### ISSUE TITLE
Generating resolver types

### ISSUE THREAD

**Issue by liftM** [prisma/prisma-binding#177]
I'd like to be able to generate TypeScript types for my server-side resolvers. This way, I can update my `app.graphql` application schema, generate the resolver types for the new schema, and statically type-check my current resolver implementations against the generated types.

This seems like the most straightforward way to write type-safe resolvers. Is there a way to do this?

See also: https://github.com/apollographql/graphql-tools/issues/404 and https://github.com/prismagraphql/prisma-binding/issues/14.

**Comment by maticzav** [comment]
Hey @liftM 👋,

That's an interesting question! I recommend you check out the `graphqlgen` project that we recently unveiled. I'll close the issue because we are trying to gain a better overview of the issues concerning the current version of `prisma-binding`, however, feel free to reopen it at any time 🙂
