### ISSUE TITLE
Invalid secret doesn't throw error on startup

### ISSUE THREAD

**Issue by kMeillet** [prisma/prisma-binding#178]
If you provide invalid secret Prisma-Binding will not throw any error unless request is performed.

I'm using Yoga server,  logs 📁 : 

```
# err1
[GraphQL error]: Message:  Your token is invalid. It might have expired or you might be using a token from a different project., Location: undefined, Path: undefined

# err2
[Network error]: Error:  Your token is invalid. It might have expired or you might be using a token from a different project.

# err3
Error:  Your token is invalid. It might have expired or you might be using a token from a different project.
    at BatchedGraphQLClient.<anonymous> (/packages/graphql/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:69:35)
    at step (/packages/graphql/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/packages/graphql/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/packages/graphql/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7
```

It would be nice to have the opportunity to test this because the error message is cryptic and it is possible to be confused quickly (people may wonder "is it the authentication of my GraphQL server that does not work or Prisma things ?").

**Comment by maticzav** [comment]
Hey @kMeillet, this entirely depends on your implementation. If you were, for example, to implement Prisma as one global instance instead of per-context one, you would receive an error immediately, if I am not mistaken.

To implement the functionality you requested, we would need to make a lot of design decisions which are very specific to such use case. Usually, such specifics turn out to be a bad practice. However, we would love to hear if you have a particular idea about the implementation of such functionality.

I'll close the issue because we are trying to gain some clarity over issues which concern the current version of `prisma-binding` but feel free to reopen it if you believe we should further address its content. 🙂
