### ISSUE TITLE
How to issue some mutation using more sophisticated sql

### ISSUE THREAD

**Issue by xiechao06** [prisma/prisma-binding#230]
Sorry, I am a newbie to `prisma-binding`, I just want to know how to make some mutation like the following sql statements:

```
INSERT INTO users (email, pwd_hash) VALUES
(:email, crypt(:password, gen_salt('md5')));
```

since sometimes I must write some sophisticated sql statements. 

Thanks!

**Comment by maticzav** [comment]
Hey @xiechao06 👋,

Sending SQL statements to Prisma is not yet available. I'll close the issue because we are trying to gain more clarity over the issues concerning most recent versions of `prisma-binding`, however, feel free to reopen the issue at any time if you believe we should further discuss its content.

Also, try checking the `prisma/prisma` repository for a similar issue or open one for yourself.

I hope this helps you with your question! 🙂
