### ISSUE TITLE
Feature: Add API for management api of the prisma server

### ISSUE THREAD

**Issue by w0wka91** [prisma/prisma-binding#235]
It would be nice if we could access the management api of the prisma server through the binding.

It could look like this:
<pre><code>
// Instantiate `Prisma` based on concrete service
const prisma = new Prisma({
  typeDefs: 'schemas/database.graphql',
  endpoint: 'https://us1.prisma.sh/demo/my-service/dev',
  secret: 'my-super-secret-secret',
  managementApiSecret: 'very-secret'
})

// Retrieve `migrationStatus` of a specific service
prisma.query.migrationStatus({name: 'service', stage:'stage}, '{ projectId }')

// Retrieve all `projects/services` the caller has access to
prisma.query.listProjects(null, '{ name }')

// Retrieve a specific `project/service`
prisma.query.project({name: 'service', stage:'stage}, '{ projectId }')

// Deploy a specific `project/service`
prisma.mutation.deploy(input: DeployInput!, '{ clientMutationId }')

// ... and all the other available mutations/queries
</pre></code>
It should supply access to all available operations <https://www.prisma.io/docs/operate-prisma-server/management-api-foe1/>

**Comment by maticzav** [comment]
Hey 👋,

I believe you can already do this by using `localhost:4466` as an endpoint. Bear in mind, however, that you should change the endpoint of the remote schema used in code generation step.

```ts
const prisma = new Prisma({
  typeDefs: 'schemas/database.graphql',
  endpoint: 'http://localhost:4466',
  secret: 'management'
})
```

I'll close the issue because we are trying to gain clarity over the issues concerning the latest version of `prisma-binding` but feel free to reopen it at any time. 🙂
