### ISSUE TITLE
It would be good if this library can connect to Elixir :D

### ISSUE THREAD

**Issue by cheuk3** [prisma/prisma-binding#240]
It would be good if this library can connect to Elixir :D

**Comment by maticzav** [comment]
@cheuk3, I believe connecting `prisma-binding` to any GraphQL work should form without any problems. Take note however that some functionality is limited to Prisma. Therefore, I would advise you check out `graphql-binding` as well.

I'll close the issue because we are trying to gain a better overview of the issues concerning the latest versions of `prisma-binding`, however, feel free to reopen it at any time! 🙂
