### ISSUE TITLE
Re-use application fields to filter data from database

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-binding#5]
It's a common scenario that you're adding a new (computed) field to your application schema. It would be great if there was a way to filter data from the database based on this field.

This might also require a new feature in the Graphcool database.

**Comment by kbrandwijk** [comment]
I would like a recipes section somewhere in the docs (advancedgraphql?) to put these things in. Because this is already possible.

- Add your root query field to your schema
- Use a new Type as filter
- Add your own fields + backend supported filter fields to that type
- When passing in args to your delegate in the resolver, only use the backend supported fields
- In that same resolver, filter the backend results on your own field.
- Return filtered results

**Comment by schickling** [comment]
That's awesome @kbrandwijk. We'll certainly add a section like this to the docs. Can you already paste a code example?

**Comment by marktani** [comment]
I am collecting such recipes here: https://github.com/graphql-boilerplates/node-graphql-server/issues/35

Would be super cool if you can add a new recipe for this use case. :)
We can then take these and add to a specific place (docs, advancedgraphql or somewhere else).

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current `prisma-binding`.

Feel free to reopen the issue if you believe it hasn't been resolved 🙂
